# Generated by Django 3.2.25 on 2024-05-11 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('debt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженость (копеек)')),
                ('creation_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='trade_network.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
