# Generated by Django 3.2.25 on 2024-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_network', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
                ('dealers', models.ManyToManyField(related_name='products', to='trade_network.Supplier', verbose_name='Дилеры')),
            ],
        ),
    ]
