# Generated by Django 3.2.25 on 2024-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_network', '0004_auto_20240511_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Частный предприниматель')], default=0, verbose_name='Тип поставщика'),
        ),
    ]
